package it.marcodemartino.common.json;

public enum JSONMethods {

    REGISTER_EMAIL,
    REGISTRATION_RESULT,
    REQUEST_PUBLIC_KEY,
    SEND_PUBLIC_KEY,
    EMAIL_VERIFICATION,
    IDENTITY_CERTIFICATE,
    ENCRYPTED_MESSAGE,
    ENCRYPTED_SIGNED_MESSAGE,

}
